# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 1000)
        MainWindow.setStyleSheet("*{\n"
                                 "border:none;\n"
                                 "background-color:transparent;\n"
                                 "background:none;\n"
                                 "padding:0;\n"
                                 "margin:0;\n"
                                 "    color:#fff;\n"
                                 "}\n"
                                 "#centralwidget{\n"
                                 "background-color:#1f232a;\n"
                                 "}\n"
                                 "#leftMenuContainer{\n"
                                 "background-color:#1f232a;\n"
                                 "}\n"
                                 "#leftsub{\n"
                                 "background-color:#16191d;\n"
                                 "}\n"
                                 "QPushButton{\n"
                                 "text-align:left;\n"
                                 "padding:1px 10px;\n"
                                 "}\n"
                                 "#mainbody{\n"
                                 "    background-color:#1f232a;\n"
                                 "}\n"
                                 "#page_emod{\n"
                                 "    background-color:#81808c;\n"
                                 "}\n"
                                 "#page_da{\n"
                                 "    background-color:#81808c;\n"
                                 "}\n"
                                 "#page_home{\n"
                                 "    background-color:#81808c;\n"
                                 "}\n"
                                 "#page_report{\n"
                                 "    background-color:#81808c;\n"
                                 "}\n"
                                 "#emoD_btn{\n"
                                 "border-style: dashed; /* 设置边框样式为虚线 */\n"
                                 "    border-width: 1px; /* 设置边框宽度 */\n"
                                 "    border-color: #000000; /* 设置边框颜色，可以更改为其他颜色值 */\n"
                                 "    border-radius: 10px; /* 设置按钮的弧度，可以更改为其他数值 */\n"
                                 "} \n"
                                 "#report_btn{border-style: dashed; /* 设置边框样式为虚线 */\n"
                                 "    border-width: 1px; /* 设置边框宽度 */\n"
                                 "    border-color: #000000; /* 设置边框颜色，可以更改为其他颜色值 */\n"
                                 "    border-radius: 10px; /* 设置按钮的弧度，可以更改为其他数值 */\n"
                                 "}\n"
                                 "#da_btn{\n"
                                 "border-style: dashed; /* 设置边框样式为虚线 */\n"
                                 "    border-width: 1px; /* 设置边框宽度 */\n"
                                 "    border-color: #000000; /* 设置边框颜色，可以更改为其他颜色值 */\n"
                                 "    border-radius: 10px; /* 设置按钮的弧度，可以更改为其他数值 */\n"
                                 "}\n"
                                 "#selectphoto{\n"
                                 "border-style: dashed; /* 设置边框样式为虚线 */\n"
                                 "    border-width: 1px; /* 设置边框宽度 */\n"
                                 "    border-color: #000000; /* 设置边框颜色，可以更改为其他颜色值 */\n"
                                 "    border-radius: 10px; /* 设置按钮的弧度，可以更改为其他数值 */\n"
                                 "}\n"
                                 "#page_emod{\n"
                                 "    border-image: url(:/icons/R.png);\n"
                                 "}\n"
                                 "#page_da{\n"
                                 "    border-image: url(:/icons/borderimage.png);\n"
                                 "}\n"
                                 "#page_home{\n"
                                 "    \n"
                                 "    border-image: url(:/icons/png.jpg);\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenuContainer = QtWidgets.QWidget(self.centralwidget)
        self.leftMenuContainer.setObjectName("leftMenuContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftMenuContainer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.leftsubcon = QtWidgets.QWidget(self.leftMenuContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftsubcon.sizePolicy().hasHeightForWidth())
        self.leftsubcon.setSizePolicy(sizePolicy)
        self.leftsubcon.setObjectName("leftsubcon")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftsubcon)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.leftsubcon)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menuBtn = QtWidgets.QPushButton(self.frame)
        self.menuBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuBtn.setIcon(icon)
        self.menuBtn.setIconSize(QtCore.QSize(128, 128))
        self.menuBtn.setObjectName("menuBtn")
        self.verticalLayout_3.addWidget(self.menuBtn)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.leftsubcon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.emoD_btn = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(22)
        font.setItalic(True)
        self.emoD_btn.setFont(font)
        self.emoD_btn.setStyleSheet("color:white;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/image.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.emoD_btn.setIcon(icon1)
        self.emoD_btn.setIconSize(QtCore.QSize(64, 64))
        self.emoD_btn.setObjectName("emoD_btn")
        self.verticalLayout_4.addWidget(self.emoD_btn)
        self.report_btn = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(22)
        font.setItalic(True)
        self.report_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/printer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.report_btn.setIcon(icon2)
        self.report_btn.setIconSize(QtCore.QSize(64, 64))
        self.report_btn.setObjectName("report_btn")
        self.verticalLayout_4.addWidget(self.report_btn)
        self.da_btn = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(22)
        font.setItalic(True)
        self.da_btn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.da_btn.setIcon(icon3)
        self.da_btn.setIconSize(QtCore.QSize(64, 64))
        self.da_btn.setObjectName("da_btn")
        self.verticalLayout_4.addWidget(self.da_btn, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.frame_3 = QtWidgets.QFrame(self.leftsubcon)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(128, 128))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_5.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignLeft)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_5.addWidget(self.pushButton_6)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.leftsubcon)
        self.horizontalLayout.addWidget(self.leftMenuContainer)
        self.mainbody = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainbody.sizePolicy().hasHeightForWidth())
        self.mainbody.setSizePolicy(sizePolicy)
        self.mainbody.setStyleSheet("")
        self.mainbody.setObjectName("mainbody")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.mainbody)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.mainbody)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.verticalLayout_6.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight)
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainbody)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.label = QtWidgets.QLabel(self.page_home)
        self.label.setGeometry(QtCore.QRect(10, 10, 1031, 51))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(22)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_home)
        self.page_emod = QtWidgets.QWidget()
        self.page_emod.setObjectName("page_emod")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_emod)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.page_emod)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(-10, 0, 481, 441))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.selectphoto = QtWidgets.QPushButton(self.frame_12)
        self.selectphoto.setGeometry(QtCore.QRect(40, 10, 271, 171))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(24)
        font.setItalic(True)
        self.selectphoto.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/camera.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectphoto.setIcon(icon5)
        self.selectphoto.setIconSize(QtCore.QSize(64, 64))
        self.selectphoto.setObjectName("selectphoto")
        self.pred = QtWidgets.QLabel(self.frame_12)
        self.pred.setGeometry(QtCore.QRect(40, 220, 271, 91))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(24)
        font.setItalic(True)
        self.pred.setFont(font)
        self.pred.setObjectName("pred")
        self.pred_result = QtWidgets.QLabel(self.frame_12)
        self.pred_result.setGeometry(QtCore.QRect(40, 310, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.pred_result.setFont(font)
        self.pred_result.setText("")
        self.pred_result.setObjectName("pred_result")
        self.photo = QtWidgets.QLabel(self.frame_11)
        self.photo.setGeometry(QtCore.QRect(499, 120, 500, 500))
        self.photo.setText("")
        self.photo.setObjectName("photo")
        self.horizontalLayout_4.addWidget(self.frame_11)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.page_emod)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7.addWidget(self.frame_10)
        self.stackedWidget.addWidget(self.page_emod)
        self.page_report = QtWidgets.QWidget()
        self.page_report.setStyleSheet("#page_report{\n"
                                       "    border-image: url(:/icons/2.jpg);\n"
                                       "}")
        self.page_report.setObjectName("page_report")
        self.label_3 = QtWidgets.QLabel(self.page_report)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 471, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(26)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_chart = QtWidgets.QLabel(self.page_report)
        self.label_chart.setGeometry(QtCore.QRect(280, 210, 601, 451))
        self.label_chart.setText("")
        self.label_chart.setObjectName("label_chart")
        self.label_chart.raise_()
        self.label_3.raise_()
        self.stackedWidget.addWidget(self.page_report)
        self.page_da = QtWidgets.QWidget()
        self.page_da.setStyleSheet("\n"
                                   "#frame_14{\n"
                                   "    border-image: url(:/icons/7045e153cc0abe61d8a27e676f84c1c.png);\n"
                                   "}\n"
                                   "#frame_15{\n"
                                   "    \n"
                                   "    border-image: url(:/icons/7159de88b9f5080a0af46f4c968c5ff.png);\n"
                                   "}\n"
                                   "#frame_16{\n"
                                   "    \n"
                                   "    border-image: url(:/icons/ceeac40f1815373d9080c43f2a63d10.png);\n"
                                   "}\n"
                                   "#frame_17{\n"
                                   "    \n"
                                   "    border-image: url(:/icons/ad78a41bf1d80d329cbbf484cbf121e.png);\n"
                                   "}")
        self.page_da.setObjectName("page_da")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_da)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_13 = QtWidgets.QFrame(self.page_da)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_8.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_8.addWidget(self.frame_15)
        self.frame_15.raise_()
        self.frame_14.raise_()
        self.horizontalLayout_3.addWidget(self.frame_13)
        self.frame_8 = QtWidgets.QFrame(self.page_da)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_16 = QtWidgets.QFrame(self.frame_8)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_9.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_8)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_9.addWidget(self.frame_17)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.page_da)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.frame_5 = QtWidgets.QFrame(self.mainbody)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.mainbody)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setToolTip(_translate("MainWindow",
                                         "<html><head/><body><p>#centralwidget{</p><p>  background-color:#1f232a;</p><p>}</p></body></html>"))
        self.emoD_btn.setText(_translate("MainWindow", "Emotion Detection"))
        self.report_btn.setText(_translate("MainWindow", "Report                   "))
        self.da_btn.setText(_translate("MainWindow", "Data Analysis        "))
        self.page_home.setToolTip(
            _translate("MainWindow", "<html><head/><body><p><img src=\":/icons/airplay.svg\"/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Facial Emotion Detection And Health Data Analysis"))
        self.selectphoto.setText(_translate("MainWindow", "Select Photo"))
        self.pred.setText(_translate("MainWindow", "Predicted label:"))
        self.label_3.setText(_translate("MainWindow", "Emotion detection report"))


import resource_rc
